import { Template } from './types';
import { 
    DEFAULT_EXCHANGE_RATE, 
    HARAMAIN_TRAIN_ACTUAL_COST_SAR, 
    DEFAULT_VISA_FEE_SAR,
    DEFAULT_BREAKFAST_COST_SAR,
    CUSTOM_TRANSPORT_ROUTES,
    CUSTOM_TRANSPORT_VEHICLES
} from './constants';

const initialCustomRoutes = Object.keys(CUSTOM_TRANSPORT_ROUTES).reduce((acc, key) => {
    acc[key] = false;
    return acc;
}, {} as Record<string, boolean>);

const initialCustomVehicles = Object.keys(CUSTOM_TRANSPORT_VEHICLES).reduce((acc, key) => {
    acc[key] = 0;
    return acc;
}, {} as Record<string, number>);

const advancedCustomizationDefaults = {
  adultsWithHaramain: 0,
  childrenWithHaramain: 0,
  adultsWithZiyarah: 0,
  childrenWithZiyarah: 0,
  customFoodAdults: 0,
  customFoodChildren: 0,
  customAccommodationAdults: 0,
  customAccommodationChildren: 0,
  customGuideAdults: 0,
  customGuideChildren: 0,
};

export const PREDEFINED_TEMPLATES: Template[] = [
  {
    name: '১৪ দিনের ইকোনমি প্যাকেজ',
    inputs: {
      packageCategory: 'ইকোনমি',
      adultMales: 2,
      adultFemales: 2,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 13,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'transit',
      airlineName: 'এয়ার আরাবিয়া/ইন্ডিগো/সালাম/ইজিপ্ট/গাল্ফ',
      airfareAdultBDT: 85000,
      airfareChildDiscount: 25,
      makkahHotelName: 'লুলু আল ইমান / শুরুক আল মিসক (বা সমমানের)',
      madinahHotelName: 'দার আল সালাম / লুলুয়াত আল কুবা ২ / হায়া আল তায়বা',
      makkahHotelCostSAR: 150,
      madinahHotelCostSAR: 150,
      personsPerRoom: 5,
      totalRooms: '',
      transportType: 'shared',
      privateTransportVehicleType: '',
      privateTransportCostSAR: 0,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 2000,
      otherChargesPerPersonBDT: 1500,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 130000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১৪ দিনের স্ট্যান্ডার্ড প্যাকেজ',
    inputs: {
      packageCategory: 'স্ট্যান্ডার্ড',
      adultMales: 2,
      adultFemales: 2,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 13,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'সৌদি / বিমান বাংলাদেশ',
      airfareAdultBDT: 95000,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল খলিল / দার আল-খলিল আর রুশাদ / লুলু আল দার',
      madinahHotelName: 'রাওয়াফেদ আল মদিনা / দিয়ার আল নূর / তাজ ওয়ার্ল্ড',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'shared',
      privateTransportVehicleType: '',
      privateTransportCostSAR: 0,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 140000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১৪ দিনের প্রিমিয়াম প্যাকেজ',
    inputs: {
      packageCategory: 'প্রিমিয়াম',
      adultMales: 2,
      adultFemales: 0,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 13,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'সৌদি / বিমান বাংলাদেশ',
      airfareAdultBDT: 110000,
      airfareChildDiscount: 25,
      makkahHotelName: 'আরিজ আল ফালাহ / লুলুআত ফালাহ/নাওয়ারাত আল শামস',
      madinahHotelName: 'মারজান গোল্ডেন / আল মদিনা গোল্ডেন/করম আল হিজাজ',
      makkahHotelCostSAR: 500,
      madinahHotelCostSAR: 500,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'GMC / Staria',
      privateTransportCostSAR: 1500,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: 50,
      guideFeePerPersonBDT: 5000,
      otherChargesPerPersonBDT: 3000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 180000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১০ দিনের ভিআইপি প্যাকেজ',
    inputs: {
      packageCategory: 'ভিআইপি',
      adultMales: 1,
      adultFemales: 1,
      childrenWithFood: 0,
      childrenWithoutFood: 1,
      infants: 1,
      totalNights: 9,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'breakfastOnly',
      flightType: 'direct',
      airlineName: 'সৌদি / বিমান বাংলাদেশ',
      airfareAdultBDT: 95000,
      airfareChildDiscount: 25,
      makkahHotelName: 'পুলম্যান জমজম টাওয়ার / মুভ এন পিক / হিলটন',
      madinahHotelName: 'পুলম্যান জমজম / মুভ এন পিক / হিলটন',
      makkahHotelCostSAR: 1000,
      madinahHotelCostSAR: 1000,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'GMC / Staria',
      privateTransportCostSAR: 1500,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: 50,
      guideFeePerPersonBDT: 5000,
      otherChargesPerPersonBDT: 3000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 250000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১০ দিনের কাস্টমাইজড প্যাকেজ (৪ জন)',
    inputs: {
      packageCategory: 'কাস্টমাইজড (৪ জন)',
      adultMales: 2,
      adultFemales: 2,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 9,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'সৌদি / বিমান বাংলাদেশ',
      airfareAdultBDT: 95000,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল খলিল / দার আল-খলিল আর রুশাদ / লুলু আল দার',
      madinahHotelName: 'রাওয়াফেদ আল মদিনা / দিয়ার আল নূর / তাজ ওয়ার্ল্ড',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1100,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
     sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 140000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
   {
    name: '৭ দিনের কাস্টমাইজড প্যাকেজ (৪ জন)',
    inputs: {
      packageCategory: 'কাস্টমাইজড (৪ জন)',
      adultMales: 2,
      adultFemales: 2,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 6,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'সৌদি / বিমান বাংলাদেশ',
      airfareAdultBDT: 95000,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল খলিল / দার আল-খলিল আল রুশাদ / লুলু আল দার',
      madinahHotelName: 'রাওয়াফেদ আল মদিনা / দিয়ার আল নূর / তাজ ওয়ার্ল্ড',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1000,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 135000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '৭ দিনের কাস্টমাইজড (২ জন)',
    inputs: {
      packageCategory: 'কাস্টমাইজড (২ জন)',
      adultMales: 1,
      adultFemales: 1,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 6,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'সৌদি এয়ারলাইন্স / বিমান বাংলাদেশ',
      airfareAdultBDT: 95000,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল-খলিল / দার আল-খলিল আল রুশাদ / লুলু আল দার',
      madinahHotelName: 'করম আল হিজাম / দিয়ার আল নুর / করম সিলভার',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 2,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1000,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
     sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 153000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১০ দিনের কাস্টমাইজড (২ জন)',
    inputs: {
      packageCategory: 'কাস্টমাইজড (২ জন)',
      adultMales: 1,
      adultFemales: 1,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 9,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'সৌদি এয়ারলাইন্স / বিমান বাংলাদেশ',
      airfareAdultBDT: 95000,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল-খলিল / দার আল-খলিল আল রুশাদ / লুলু আল দার',
      madinahHotelName: 'করম আল হিজাম / দিয়ার আল নুর / করম সিলভার',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 2,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1100,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
       sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 147000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১৪ দিনের কাপল ইকোনমি',
    inputs: {
      packageCategory: 'কাপল ইকোনমি',
      adultMales: 1,
      adultFemales: 1,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 13,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'transit',
      airlineName: 'ফ্লাই দুবাই/এয়ার আরাবিয়া/ইন্ডিগো/ইন্ডিয়া/সালাম',
      airfareAdultBDT: 85000,
      airfareChildDiscount: 25,
      makkahHotelName: 'লুলু আল ইমান / হোটেল জাহরাত আল ফালাহ / শুরুক আল মিসক',
      madinahHotelName: 'দার আল সালাম / লুলুয়াত আল কুবা ২ / হায়া আল তায়বা',
      makkahHotelCostSAR: 170,
      madinahHotelCostSAR: 170,
      personsPerRoom: 2,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1200,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
       sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 2000,
      otherChargesPerPersonBDT: 1500,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 150000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১৪ দিনের কাপল স্ট্যান্ডার্ড',
    inputs: {
      packageCategory: 'কাপল স্ট্যান্ডার্ড',
      adultMales: 1,
      adultFemales: 1,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 13,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'সৌদি এয়ারলাইন্স / বিমান বাংলাদেশ',
      airfareAdultBDT: 95000,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল-খলিল / দার আল-খলিল আল রুশাদ / লুলু আল দার',
      madinahHotelName: 'রাওয়াফেদ আল মদিনা / দিয়ার আল নুর / তাজ ওয়ার্ল্ড',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 2,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1200,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
       sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 160000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '৭ দিনের ল্যান্ড প্যাকেজ (৪ জন)',
    inputs: {
      packageCategory: 'কাস্টমাইজড (৪ জন)',
      adultMales: 2,
      adultFemales: 2,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 6,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'পছন্দমত এয়ারলাইন্স',
      airfareAdultBDT: 0,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল খলিল / দার আল-খলিল আল রুশাদ / লুলু আল দার',
      madinahHotelName: 'তাজ ওয়ার্ল্ড / দিয়ার আল নুর / রাওয়াফেদ আল মদীনা',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1000,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 84500,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১০ দিনের ল্যান্ড প্যাকেজ (৪ জন)',
    inputs: {
      packageCategory: 'কাস্টমাইজড (৪ জন)',
      adultMales: 2,
      adultFemales: 2,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 9,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'পছন্দমত এয়ারলাইন্স',
      airfareAdultBDT: 0,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল খলিল / দার আল-খলিল আল রুশাদ / লুলু আল দার',
      madinahHotelName: 'তাজ ওয়ার্ল্ড / দিয়ার আল নুর / রাওয়াফেদ আল মদীনা',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1100,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 85500,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  },
  {
    name: '১৪ দিনের ল্যান্ড প্যাকেজ (৪ জন)',
    inputs: {
      packageCategory: 'কাস্টমাইজড (৪ জন)',
      adultMales: 2,
      adultFemales: 2,
      childrenWithFood: 0,
      childrenWithoutFood: 0,
      infants: 0,
      totalNights: 13,
      sarToBdtRate: DEFAULT_EXCHANGE_RATE,
      foodPlan: 'none',
      flightType: 'direct',
      airlineName: 'পছন্দমত এয়ারলাইন্স',
      airfareAdultBDT: 0,
      airfareChildDiscount: 25,
      makkahHotelName: 'ইমার আল খলিল / দার আল-খলিল আল রুশাদ / লুলু আল দার',
      madinahHotelName: 'তাজ ওয়ার্ল্ড / দিয়ার আল নুর / রাওয়াফেদ আল মদীনা',
      makkahHotelCostSAR: 180,
      madinahHotelCostSAR: 180,
      personsPerRoom: 4,
      totalRooms: '',
      transportType: 'private',
      privateTransportVehicleType: 'Sedan Car',
      privateTransportCostSAR: 1200,
      visaCostPerPersonSAR: DEFAULT_VISA_FEE_SAR,
      sharedJeddahMakkahSAR: 30,
      sharedMakkahZiyarahSAR: 15,
      sharedMakkahMadinahSAR: 50,
      sharedMadinahZiyarahSAR: 15,
      sharedMadinahAirportSAR: 20,
      customTransportVehicles: initialCustomVehicles,
      customTransportRoutes: initialCustomRoutes,
      foodCostPerDaySAR: 20,
      breakfastCostPerDaySAR: DEFAULT_BREAKFAST_COST_SAR,
      guideFeePerPersonBDT: 3000,
      otherChargesPerPersonBDT: 2000,
      mehmandariCostBDT: 0,
      jorimanaCostBDT: 0,
      haramainTrainIncluded: false,
      haramainTrainActualCostSAR: HARAMAIN_TRAIN_ACTUAL_COST_SAR,
      packagePricePerAdultBDT: 60000,
      infantCostBDT: 50000,
      overallDiscountBDT: 0,
      ...advancedCustomizationDefaults
    }
  }
];